services:
  grafana:
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/no_folder/Syslog_AIO_Overview.json
    image: grafana/grafana:8.1.2
    ports:
    - protocol: tcp
      published: 3000
      target: 3000
    restart: unless-stopped
    volumes:
    - ${CONFIG}/syslog-aio/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    - ${CONFIG}/syslog-aio/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ${CONFIG}/syslog-aio/grafana/dashboards:/var/lib/grafana/dashboards

networks:
  default:
    external: true
    name: om