services:
  proxy-om:
    container_name: nginx-proxy-om
    image: 'jc21/nginx-proxy-manager:latest'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      # - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/nginxproxyom/data:/data
      - CHANGE_TO_COMPOSE_DATA_PATH/nginxproxyom/letsencrypt:/etc/letsencrypt

networks:
  default:
    external: true
    name: om