volumes:
  minio-data:
    external: true
    name: minio_data

networks:
  default:
    external: true
    name: om
    
services:
  loki:
    command: -config.file=/etc/loki/loki-config.yml
    container_name: loki
    depends_on:
    - minio
    image: grafana/loki:2.3.0
    restart: unless-stopped
    volumes:
    - ${CONFIG}/syslog-aio/loki-config-s3.yml:/etc/loki/loki-config.yml:ro
  minio:
    command: -c 'mkdir -p /data/loki && /usr/bin/docker-entrypoint.sh minio server /data'
    container_name: minio
    entrypoint: sh
    environment:
      MINIO_ACCESS_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_SECRET_KEY: minio456
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - curl
      - -f
      - http://localhost:9000/minio/health/live
      timeout: 20s
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
    - minio-data:/data
  promtail:
    command: -config.file=/etc/promtail/promtail-config.yml
    container_name: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
    - ${CONFIG}/syslog-aio/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
  syslog-ng:
    command: -edv
    container_name: syslog-ng
    depends_on:
    - promtail
    image: balabit/syslog-ng:latest
    ports:
    - protocol: udp
      published: 514
      target: 514
    restart: unless-stopped
    volumes:
    - ${CONFIG}/syslog-aio/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf:ro